### ISSUE TITLE
needing a file

### ISSUE THREAD

**Issue by noorollahih** [gevero/py_gmm#1]
I run the program" f2py" on windows platform then receive the alert "f2py3 is not recognized as an input or output or patch file  " . please help me.

**Comment by gevero** [comment]
I have two suggestions for you:
- substitute f2py3 with f2py inside the f2py.sh script or...
- create a python3.4 environment with conda using the environment.yml file inside the repository (Google conda environment management to see how to do it)

If it does not work let me know

**Comment by gevero** [comment]
Check how many environment you have with the following command: `conda info --envs`

Then you can create the proper environment like this: `conda env create -f environment.yml`

The just appeared environment is the right one.

Finally you can activate it like this: `
activate your_env`
