### ISSUE TITLE
Is it possible to use this program to model the behavior of photons in dirty ice?

### ISSUE THREAD

**Issue by StevenSpohrer** [gevero/py_gmm#10]
Hello,

I am currently working on subsurface heating in Pluto's N_2 ice layer in which photons are trapped by the N2 ice and are scattered/absorbed by "dirty" particles in the ice called tholins. I am trying to figure out how many photons would be absorbed/reflected/transmitted per unit volume of this dirty N2 ice. Is this possible to do with this code?

**Comment by gevero** [comment]
Hi Steven

I can tell you what my code can do. It can model the optical properties of arbitrary cluster (hundreds of sphere) of spheres in a fixed orientation. You can compute the following quantities:

- Extinction, Scattering and Absorption Cross sections
- Scattering matrix
- Local Fields

Then I guess you can bridge the gap between these quantities and what you want to compute.

Best

Giovanni

**Comment by StevenSpohrer** [comment]
Thank you!
