### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by limjoowon** [gevero/py_gmm#11]
Hello,

My name is Won.
I tried to use ur software but couldn't. I think there is a problem in the compiling.
At the end of compilation (sh f2py.sh), it shows the following,

error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared ./tmp/tmp/src.linux-x86_64-3.5/gmm_pymodule.o ./tmp/tmp/src.linux-x86_64-3.5/fortranobject.o ./tmp/kinds.o ./tmp/datatypes.o ./tmp/operators.o ./tmp/shared_data.o ./tmp/basicsubs.o ./tmp/gmmsubs.o ./tmp/sing_part.o ./tmp/vec_trans.o ./tmp/local_field.o ./tmp/linear_solver.o ./tmp/gmm_f2py_module.o ./tmp/tmp/src.linux-x86_64-3.5/gmm_py-f2pywrappers2.o -L/home/user-linux/anaconda3/lib -lopenblas -lpython3.5m -lgfortran -o ./gmm_py.cpython-35m-x86_64-linux-gnu.so" failed with exit status 1

The versions I am using are as followings,

**Ubuntu** : 17.04
**Python** : 3.6.1
**Gfortran** : GNU Fortran (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
**Conda**
- platform : linux-64
- conda version : 4.3.22
- conda is private : False
- conda-env version : 4.3.22
- conda-build version : 2.0.2
- python version : 3.5.3.final.0
- requests version : 2.14.2
       
Do you have any comments about it?

Best,

Won.

**Comment by gevero** [comment]
Hi Won

Would you be so kind to create a gist containing all the output of all the compilation steps and link it here. So I can see what's going on and provide you with a solution.

Best

Giovanni

**Comment by limjoowon** [comment]
Hello Giovanni,

Thank you for your prompt reply.
I am pretty new to the Github and I hope this is what you meant.
https://gist.github.com/limjoowon/945153a836f504488cf08f841871c7a7

Best,

Won

**Comment by gevero** [comment]
Hi Won

Perfect! Install the openblas library with the 'conda install openblas' command, and it should work. Let me know if everything is ok.

Best

Giovanni

**Comment by limjoowon** [comment]
Hi Giovanni,

Thank you very much!
It works!!

Best,

Won.
