### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by limjoowon** [gevero/py_gmm#12]
Hello,

My name is JooWon and thank you very much for sharing the program.
Last time, I could set the program and run it.

I had deleted everything so I now try to set up again.
But I encountered the problem. When I enter f2py.sh, I see the following message at the end.

creating tmp/tmp
creating tmp/tmp/src.linux-x86_64-3.6
creating tmp/tmp/src.linux-x86_64-3.6/tmp
creating tmp/tmp/src.linux-x86_64-3.6/tmp/src.linux-x86_64-3.6
compile options: '-I./tmp/src.linux-x86_64-3.6/tmp/src.linux-x86_64-3.6 -I/home/joowon/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/joowon/anaconda3/include/python3.6m -c'
x86_64-conda_cos6-linux-gnu-gcc: tmp/src.linux-x86_64-3.6/gmm_pymodule.c
/bin/bash: x86_64-conda_cos6-linux-gnu-gcc: command not found
/bin/bash: x86_64-conda_cos6-linux-gnu-gcc: command not found
error: Command "x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -I./tmp/src.linux-x86_64-3.6/tmp/src.linux-x86_64-3.6 -I/home/joowon/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/home/joowon/anaconda3/include/python3.6m -c tmp/src.linux-x86_64-3.6/gmm_pymodule.c -o ./tmp/tmp/src.linux-x86_64-3.6/gmm_pymodule.o -MMD -MF ./tmp/tmp/src.linux-x86_64-3.6/gmm_pymodule.o.d" failed with exit status 127

Could you give me any comments?

With my best,

JooWon.

**Comment by gevero** [comment]
It looks like you are missing gcc. Try and install it with your distribution or with conda.

**Comment by limjoowon** [comment]
Hi,

I checked the version of gcc using gcc -v :

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.3.0-12ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 

Is it the problem of version that I am using it?

Best,

JooWon.

**Comment by gevero** [comment]
looks like an anaconda bug. look here for possible solutions: https://stackoverflow.com/q/46450912/4152810

**Comment by limjoowon** [comment]
Hello,

I checked the version using gcc --v
It shows following,

**Comment by limjoowon** [comment]
Thanks!

After updating conda, it works! There must have been a bug.
Thank you very much.

I have another question.
In the folder (epsilon), there are optical parameters needed to calculate the refractive index.
I know the refractive index of a certain material (Polystyrene, both real and imaginary), is it possible to plug the RI itself directly in the function instead of putting epsilon values? 

If yes, could you tell me the name of variable or function?
If no, could you give me some comments where I can look for epsilon values for other materials?

Cheers,

JooWon.

**Comment by gevero** [comment]
Hi. Epsilon is simply the RI squared. So it's trivial to go from one to the other.

**Comment by gevero** [comment]
Hi JooWon

I will mark this issue as closed. If you need help on other matters, please do not hesitate to open a new issue.

Best

Giovanni

**Comment by limjoowon** [comment]
Hi Giovanni,

Thank you very much.
Actually I have one more question.

I will get back to you soon.

Best,

JooWon.
