### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by syou83syou83** [gevero/py_gmm#16]
Hi,

When I ran sh f2py.sh in my Ubuntu 16.04 LTS in Canopy, I found the following info. I am a beginner of python and know little about fortran. Could you tell me what happened here?  Because ImportError: No module named py_gmm, I assume it must not be installed successfully. When I was trying to run it on Binder before installation, it also showed an error: Unable to locate package libopenblas-base.  

All I want to calculate is the extinction cross section of a doublet aggregate, with each particle size about 90 micron. Thank you so much for your help. 

Reading fortran codes...
	Reading file 'gmm_f2py_module.f90' (format:free)
rmbadname1: Replacing "short" with "short_bn".
rmbadname1: Replacing "long" with "long_bn".
Post-processing...
	Block: gmm_py
			Block: local_kinds
In: :gmm_py:gmm_f2py_module.f90:local_kinds
get_parameters: got "unexpected EOF while parsing (<string>, line 1)" on '0.0d0'
			Block: gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module vec_trans info used by gmm_f2py_moduImportError: /home/sichen/.local/share/canopy/edm/envs/User/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ../py_gmm/gmm_py.so)le
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module linear_solver info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module shared_data info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module operators info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module sing_part info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module gmmsubs info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module datatypes info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module local_field info used by gmm_f2py_module
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module
get_useparameters: no module basicsubs info used by gmm_f2py_module
				Block: emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module vec_trans info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module linear_solver info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module shared_data info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module operators info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module sing_part info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module gmmsubs info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module datatypes info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module local_field info used by emn
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:emn
get_useparameters: no module basicsubs info used by emn
				Block: expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module vec_trans info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module linear_solver info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module shared_data info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module operators info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module sing_part info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module gmmsubs info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module datatypes info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module local_field info used by expansion_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:expansion_coefficients
get_useparameters: no module basicsubs info used by expansion_coefficients
				Block: exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module vec_trans info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module linear_solver info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module shared_data info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module operators info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module sing_part info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module gmmsubs info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module datatypes info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module local_field info used by exyz
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:exyz
get_useparameters: no module basicsubs info used by exyz
				Block: efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module vec_trans info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module linear_solver info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module shared_data info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module operators info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module sing_part info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module gmmsubs info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module datatypes info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module local_field info used by efar
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar
get_useparameters: no module basicsubs info used by efar
				Block: efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module vec_trans info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module linear_solver info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module shared_data info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module operators info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module sing_part info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module gmmsubs info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module datatypes info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module local_field info used by efar_poynting
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:efar_poynting
get_useparameters: no module basicsubs info used by efar_poynting
				Block: dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module vec_trans info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module linear_solver info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module shared_data info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module operators info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module sing_part info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module gmmsubs info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module datatypes info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module local_field info used by dip_coefficients
In: :gmm_py:gmm_f2py_module.f90:gmm_f2py_module:dip_coefficients
get_useparameters: no module basicsubs info used by dip_coefficients
Post-processing (stage 2)...
	Block: gmm_py
		Block: unknown_interface
			Block: local_kinds
			Block: gmm_f2py_module
				Block: emn
				Block: expansion_coefficients
				Block: exyz
				Block: efar
				Block: efar_poynting
				Block: dip_coefficients
Saving signatures to file "./gmm_py.pyf"
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "gmm_py" sources
f2py options: []
f2py: gmm_py.pyf
Reading fortran codes...
	Reading file 'gmm_py.pyf' (format:free)
Post-processing...
	Block: gmm_py
			Block: local_kinds
			Block: gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module vec_trans info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module linear_solver info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module shared_data info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module operators info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module sing_part info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module gmmsubs info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module datatypes info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module local_field info used by gmm_f2py_module
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module
get_useparameters: no module basicsubs info used by gmm_f2py_module
				Block: emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module vec_trans info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module linear_solver info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module shared_data info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module operators info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module sing_part info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module gmmsubs info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module datatypes info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module local_field info used by emn
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:emn
get_useparameters: no module basicsubs info used by emn
				Block: expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module vec_trans info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module linear_solver info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module shared_data info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module operators info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module sing_part info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module gmmsubs info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module datatypes info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module local_field info used by expansion_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:expansion_coefficients
get_useparameters: no module basicsubs info used by expansion_coefficients
				Block: exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module vec_trans info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module linear_solver info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module shared_data info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module operators info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module sing_part info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module gmmsubs info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module datatypes info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module local_field info used by exyz
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:exyz
get_useparameters: no module basicsubs info used by exyz
				Block: efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module vec_trans info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module linear_solver info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module shared_data info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module operators info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module sing_part info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module gmmsubs info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module datatypes info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module local_field info used by efar
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar
get_useparameters: no module basicsubs info used by efar
				Block: efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module vec_trans info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module linear_solver info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module shared_data info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module operators info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module sing_part info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module gmmsubs info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module datatypes info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module local_field info used by efar_poynting
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:efar_poynting
get_useparameters: no module basicsubs info used by efar_poynting
				Block: dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module vec_trans info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module linear_solver info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module shared_data info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module operators info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module sing_part info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module gmmsubs info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module datatypes info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module local_field info used by dip_coefficients
In: gmm_py.pyf:gmm_py:unknown_interface:gmm_f2py_module:dip_coefficients
get_useparameters: no module basicsubs info used by dip_coefficients
Post-processing (stage 2)...
	Block: gmm_py
		Block: unknown_interface
			Block: local_kinds
			Block: gmm_f2py_module
				Block: emn
				Block: expansion_coefficients
				Block: exyz
				Block: efar
				Block: efar_poynting
				Block: dip_coefficients
Building modules...
	Building module "gmm_py"...
		Constructing F90 module support for "local_kinds"...
		  Variables: twopi dbl short_bn pio2_d sqrt2_d sgl zerodbl e0 me c e lo vshort twopi_d length sqrt2 pio2 pi pi_d long_bn euler euler_d
undo_rmbadname1: Replacing "short_bn" with "short".
undo_rmbadname1: Replacing "long_bn" with "long".
undo_rmbadname1: Replacing "short_bn" with "short".
undo_rmbadname1: Replacing "long_bn" with "long".
undo_rmbadname1: Replacing "short_bn" with "short".
undo_rmbadname1: Replacing "long_bn" with "long".
undo_rmbadname1: Replacing "short_bn" with "short".
undo_rmbadname1: Replacing "long_bn" with "long".
		Constructing F90 module support for "gmm_f2py_module"...
			Constructing wrapper function "gmm_f2py_module.emn"...
			  v_emn,error = emn(nstop)
			Constructing wrapper function "gmm_f2py_module.expansion_coefficients"...
			  m_coeff,v_cext,v_csca,v_cabs = expansion_coefficients(m_xyz_inp,v_r_inp,m_eps_inp,fint,ref_index,lambda_inp,alpha0,beta0,gamma0,nstop,quasi_static_flag,[ns])
			Constructing wrapper function "gmm_f2py_module.exyz"...
			  ex,ey,ez,eabs,error = exyz(flaginc,nstop,ratio,lambda_inp,alpha0,beta0,gamma0,x,y,z,v_amnbmn,v_dmncmn,v_emn,m_xyz_inp,m_eps_inp,v_r_inp,ref_index,quasi_static_flag,[ns])
			Constructing wrapper function "gmm_f2py_module.efar"...
			  m_sc,scatot,error = efar(k,nstop,phimin,phimax,phistep,thetastep,betap,v_amnbmn,m_xyz_inp,[ns])
			Constructing wrapper function "gmm_f2py_module.efar_poynting"...
			  m_sc,scatot,error = efar_poynting(k,nstop,phimin,phimax,phistep,thetastep,betap,v_amnbmn,m_xyz_inp,[ns])
			Constructing wrapper function "gmm_f2py_module.dip_coefficients"...
			  m_coeff,v_w = dip_coefficients(ndip,m_xyz_inp,v_r_inp,m_eps_inp,fint,q0,ref_index,lambda_inp,alpha0,beta0,gamma0,nstop,quasi_static_flag,[ns])
	Wrote C/API module "gmm_py" to file "tmp/src.linux-x86_64-2.7/gmm_pymodule.c"
	Fortran 90 wrappers are saved to "tmp/src.linux-x86_64-2.7/gmm_py-f2pywrappers2.f90"
  adding './tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding './tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7' to include_dirs.
  adding 'tmp/src.linux-x86_64-2.7/gmm_py-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
Found executable /usr/bin/gfortran
customize Gnu95FCompiler using build_ext
building 'gmm_py' extension
compiling C sources
C compiler: gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O2 -fPIC

compile options: '-I./tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7 -I/home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include -I/home/sichen/.local/share/canopy/edm/envs/User/include/python2.7 -c'
gcc: tmp/src.linux-x86_64-2.7/gmm_pymodule.c
In file included from /home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from ./tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7/fortranobject.h:13,
                 from tmp/src.linux-x86_64-2.7/gmm_pymodule.c:19:
/home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
compiling Fortran 90 module sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -O3 -fpic -m64 -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -O3 -fpic -m64 -fPIC -O3 -funroll-loops
compile options: '-I./tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7 -I/home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include -I/home/sichen/.local/share/canopy/edm/envs/User/include/python2.7 -c'
extra options: '-J./tmp/ -I./tmp/'
gfortran:f90: kinds.f90
gfortran:f90: datatypes.f90
gfortran:f90: operators.f90
gfortran:f90: shared_data.f90
gfortran:f90: basicsubs.f90
gfortran:f90: gmmsubs.f90
gfortran:f90: sing_part.f90
gfortran:f90: vec_trans.f90
gfortran:f90: local_field.f90
gfortran:f90: linear_solver.f90
gfortran:f90: gmm_f2py_module.f90
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -O3 -fpic -m64 -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -O3 -fpic -m64 -fPIC -O3 -funroll-loops
compile options: '-I./tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7 -I/home/sichen/.local/share/canopy/edm/envs/User/lib/python2.7/site-packages/numpy/core/include -I/home/sichen/.local/share/canopy/edm/envs/User/include/python2.7 -c'
extra options: '-J./tmp/ -I./tmp/'
gfortran:f90: tmp/src.linux-x86_64-2.7/gmm_py-f2pywrappers2.f90
/usr/bin/gfortran -Wall -g -Wall -g -shared ./tmp/tmp/src.linux-x86_64-2.7/gmm_pymodule.o ./tmp/tmp/src.linux-x86_64-2.7/tmp/src.linux-x86_64-2.7/fortranobject.o ./tmp/kinds.o ./tmp/datatypes.o ./tmp/operators.o ./tmp/shared_data.o ./tmp/basicsubs.o ./tmp/gmmsubs.o ./tmp/sing_part.o ./tmp/vec_trans.o ./tmp/local_field.o ./tmp/linear_solver.o ./tmp/gmm_f2py_module.o ./tmp/tmp/src.linux-x86_64-2.7/gmm_py-f2pywrappers2.o -L/home/sichen/.local/share/canopy/edm/envs/User/lib -lopenblas -lpython2.7 -lgfortran -o ./gmm_py.so

**Comment by gevero** [comment]
Hi! 
Did you use anaconda? If yes try `conda install openblas`. Otherwise run `apt-cache search openblas` and install the relevant `openblas` packages.

**Comment by syou83syou83** [comment]
Hi Gevero,
I am using Enthought Canopy. And I did the following. But this seems doesn't work either for Binder or for my installation. 

(User)sichen@sichen:~$ apt-cache search  openblas
libblas-test - Basic Linear Algebra Subroutines 3, testing programs
libopenblas-base - Optimized BLAS (linear algebra) library (shared library)
libopenblas-dev - Optimized BLAS (linear algebra) library (development files)
(User)sichen@sichen:~$ sudo apt-get install libopenblas-dev
[sudo] password for sichen: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenblas-dev is already the newest version (0.2.18-1ubuntu1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic
  linux-headers-4.13.0-26 linux-headers-4.13.0-26-generic
  linux-image-4.10.0-28-generic linux-image-4.13.0-26-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-26-generic
  linux-oem-tools-4.13.0-1012 linux-oem-tools-4.13.0-1015
  linux-oem-tools-4.13.0-1017 linux-tools-4.13.0-1012-oem
  linux-tools-4.13.0-1015-oem linux-tools-4.13.0-1017-oem
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
(User)sichen@sichen:~$ sudo apt-get install libopenblas-base
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libopenblas-base is already the newest version (0.2.18-1ubuntu1).
libopenblas-base set to manually installed.
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic
  linux-headers-4.13.0-26 linux-headers-4.13.0-26-generic
  linux-image-4.10.0-28-generic linux-image-4.13.0-26-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.13.0-26-generic
  linux-oem-tools-4.13.0-1012 linux-oem-tools-4.13.0-1015
  linux-oem-tools-4.13.0-1017 linux-tools-4.13.0-1012-oem
  linux-tools-4.13.0-1015-oem linux-tools-4.13.0-1017-oem
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.


After running Au_dimer_scattering.ipynb, I got :
ImportError: /home/sichen/.local/share/canopy/edm/envs/User/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ../py_gmm/gmm_py.so)

**Comment by gevero** [comment]
Well, this looks like a [canopy issue](https://stackoverflow.com/questions/26183205/gfortran-1-4-not-found).

**Comment by gevero** [comment]
PS... binder platform is always changing. It used to work, but now probably i need to update the dockerfile

**Comment by syou83syou83** [comment]
Thanks gevero. I will work on it and let you know if I can solve it.

**Comment by gevero** [comment]
My advice is to use conda. It has work on many for many different users on many different platforms. Give it a try!

**Comment by gevero** [comment]
Hi

This should work

- Install docker on your machine (do this, and the following, as root if using linux)
- in the py_gmm base folder, run `docker build --tag pygmm:1.0 .` 
- run `sudo docker run --publish 8888:8888 --detach --name pygmm pygmm:1.0` to build the container and open the 8888 port for the jupyter server that is already running inside the container
- run `docker exec -it pygmm jupyter notebook list` to get the token to access the server

Best

Giovanni
