### ISSUE TITLE
References: optical constants of materials

### ISSUE THREAD

**Issue by abertoni** [gevero/py_gmm#17]
Hello Giovanni,

I am in need of the reference behind the data of the file "eAgFerreiraf.edb" (in the "epsilon" folder).
Can you please help me with that?

Thanks a lot in advance :)

Andrés.

**Comment by gevero** [comment]
Hi

This should be the paper:

1. Ferreiro-Vila E, González-Díaz JB, Fermento R, González MU, García-Martín A, García-Martín JM, Cebollada A, Armelles G, Meneses-Rodríguez D, Sandoval EM (2009) Intertwined magneto-optical and plasmonic effects in Ag/Co/Ag layered structures. Phys Rev B 80:125132 . doi: 10.1103/PhysRevB.80.125132

Of course there is a typo in the name: it should read Ferreiro and not Ferreira!

best

giovanni
