### ISSUE TITLE
Compiling fails 

### ISSUE THREAD

**Issue by pear420** [gevero/py_gmm#18]
Compiling fails on Windows. By changing the f2py.sh file to f2py.bat and running it on anaconda prompt it gets stuck repeating the same line continuously:

```
(base) C:\Users\sadbo\OneDrive for Business\Python\Tesi\py_gmm\py_gmm>f2py --overwrite-signature -m gmm_py -h gmm_py.pyf gmm_f2py_module.f90

(base) C:\Users\sadbo\OneDrive for Business\Python\Tesi\py_gmm\py_gmm>f2py --overwrite-signature -m gmm_py -h gmm_py.pyf gmm_f2py_module.f90

(base) C:\Users\sadbo\OneDrive for Business\Python\Tesi\py_gmm\py_gmm>f2py --overwrite-signature -m gmm_py -h gmm_py.pyf gmm_f2py_module.f90

(base) C:\Users\sadbo\OneDrive for Business\Python\Tesi\py_gmm\py_gmm>f2py --overwrite-signature -m gmm_py -h gmm_py.pyf gmm_f2py_module.f90
```

**Comment by gevero** [comment]
Hi Matteo

Sorry for the late answer! So, I have two suggestions for you:

- Setup a linux virtual machine and run py_gmm inside it. You probably will not like this approach, but it's the safest one
- Prepend "call" to each line in the bat file, even though I cannot guarantee that it will work

best

Giovanni

**Comment by gevero** [comment]
Hi Matteo

If this issue is solved I am going to close it.

best

giovanni

**Comment by pear420** [comment]
Thank you!
