### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by danielpickard** [gevero/py_gmm#19]
it cannot find -lopenblas when I try to compile with sh f2py.sh on ubuntu. I just installed Anaconda3. Should I download -lopenblas or openblas or something

**Comment by gevero** [comment]
If you installed with anaconda, "conda install openblas" should do the trick.

Best

Giovanni

**Comment by danielpickard** [comment]
That did not work. I cloned the repository from github. Using git clone. Is
there a Conda command I should have used?

Best
Daniel

**Comment by gevero** [comment]
Hi

This should work

Install docker on your machine (do this, and the following, as root if using linux)
in the py_gmm base folder, run docker build --tag pygmm:1.0 .
run sudo docker run --publish 8888:8888 --detach --name pygmm pygmm:1.0 to build the container and open the 8888 port for the jupyter server that is already running inside the container
run docker exec -it pygmm jupyter notebook list to get the token to access the server
Best

Giovanni
