### ISSUE TITLE
circularly polarized incident wave

### ISSUE THREAD

**Issue by kylenai** [gevero/py_gmm#20]
Hi,

How can I create left and right circularly polarized incident source?
If Euler angles: (alpha,beta,gamma)=(0,0,0) means a z-directed, x-polarized plane wave
Does (alpha,beta,gamma)=(0,0,π/2) mean a z-directed, y-polarized plane wave?
Then is z-directed left circularly polarized light (alpha,beta,gamma)=(0,0,π/4)?

**Comment by gevero** [comment]
Hi

The (alpha,beta,gamma)=(0,0,π/4) configuration just gives you linear polarization at 45 degrees. It is possible to get circular polarization, but it requires a modification (not too hard to do) at source code level. Let me know if you are interested and I shall try do implement it as soon as I have some free time.

Best

Giovanni

**Comment by kylenai** [comment]
Hi Giovanni.

Thank you for your reply. 
Yes, I am interested in circularly polarized lights, it would be great if you can implement it.

Best,

**Comment by gevero** [comment]
Hi 

I will try to do it. Unfortunately my current job does not leave me much room for this kind of side project, but I will try my best. :)

Best

Giovanni

**Comment by gevero** [comment]
Hi 

I updated the dockerfile so you can run py_gmm on binder. I shall get to the circular polarization as soon as I can. In the meantime you can use docker to try py_gmm locally:

- Install docker on your machine (do this, and the following, as root if using linux)
- in the py_gmm base folder, run `docker build --tag pygmm:1.0 .` 
- run `sudo docker run --publish 8888:8888 --detach --name pygmm pygmm:1.0` to build the container and open the 8888 port for the jupyter server that is already running inside the container
- run `docker exec -it pygmm jupyter notebook list` to get the token to access the server

Best

Giovanni

**Comment by kylenai** [comment]
Thanks Giovanni!

**Comment by gevero** [comment]
Hi

As of today I am back in academia, so I will have much more time to work on this problem. As a matter of fact I already set up an example and it seems to work reasonably well, so I hope I will be able to push the changes in a few days.

Best

Giovanni

**Comment by kylenai** [comment]
Thanks Giovanni!

Our on-going project will be greatly benefited from this new implementation.



Giovanni Pellegrini <notifications@github.com> 於 2020年10月30日 週五 上午4:09 寫道：

**Comment by kylenai** [comment]
Hi Giovanni,

Any update on the implementation of circularly polarized excitation?

Thank you again for the code, it has work well for me. I am running it embarrassingly parallelized for my system.

**Comment by gevero** [comment]
Hi

Sorry to make you wait so long. Actually I am neck deep in my teaching duties, but I will be finished by friday and I promise you that circular polarization will be up by the end of next week, along with an example. I am happy to ear that the code is working well for you. Also in my case, embarrassingly parallel was the way to go. If you feel like it, do not hesitate to contribute to the repo with a notebook example.

Best

Giovanni

**Comment by gevero** [comment]
Finally added circular polarization, along with an example. It is still work in progress, but the results seem reasonable. Please let me know if it works for you.

Best

Giovanni
