### ISSUE TITLE
Direction and polarization of the plane wave

### ISSUE THREAD

**Issue by 1br14n** [gevero/py_gmm#21]
Hi!
I'm having a bit of trouble to understand the incident field, hope you can help.

If (0,0,0) means a z-directed, x-polarized plane wave,
does ( pi/2, 0, pi/2 ) means a x-directed, y-polarized p. w. and ( pi/2, pi/2, 0) y-directed, z-polarized p. w. ?

I'm confused since azimuth is usually measured from the +z axis, and the polar in the xy-plane, but I have none experience with Euler's angles.

Thank you in advance

**Comment by gevero** [comment]
Hi

You can find all the information you need in my Ph.D [thesis](http://paduaresearch.cab.unipd.it/938/) at page 4.

Best

Giovanni

**Comment by 1br14n** [comment]
Thank you, 
that's exactly what I was looking for.
Your comment in pages 38-39 about S. et al claims was very interesting.

You mention using non polarized light for the when working with nano-planets. 
How do you set the light as non-polarized?
I could no find any clue in the examples.

Greetings!

**Comment by gevero** [comment]
Hi

Regarding your comment on non polarized light I am non really sure about how I did it at the time. I must have done it numerically by averaging the cross sections of several different illumination polarizations. Unfortunately 13 years are a long time and at the time a was less strict in term of data storage and code versioning.

I am instead absolutely sure about the comments on pg 38-39. Take a look at this [publication](https://pubs.acs.org/doi/abs/10.1021/acs.jpcc.6b08802) if you are interested.

Best

Giovanni
