### ISSUE TITLE
Export simulation results

### ISSUE THREAD

**Issue by yu-ting-py** [gevero/py_gmm#22]
Thanks for your promising code.

I would like to know how to export the simulation results after I launch "binder".  (click the button below)
![image](https://user-images.githubusercontent.com/42253517/115107174-8368d480-9f69-11eb-9386-74973dfd67ae.png)

Extinction appears successfully and how to export the simulation to my hard drive?
(ex. export as txt files)

It works without 'plotly' but radiation needs this package I guess. How to do that?

I will cite the paper if this result explains my data.

I will also try "installation in a hard way" but I'm not sure that works on Windows PC.

**Comment by gevero** [comment]
Hi

You probably should proceed as follows:

- Install [docker](https://docs.docker.com/docker-for-windows/install/) on your windows pc
- Setup docker to [share windows folders](https://docs.docker.com/docker-for-windows/).
- Clone py_gmm repository
- Build the container
- run the container
- install plotly inside the container
- run the python script. you should then be able to save file in a windows folder.

Best

Giovanni

**Comment by yu-ting-py** [comment]
Hi Giovanni

I try to use Docker but cannot share my windows folder somehow. I use WSL2 on windows 10.

I'm new to Docker. Do you have any suggestions?

**Comment by gevero** [comment]
Hi

I never run docker under windows because I am a linux user. Nevertheless, in the instruction [link](https://docs.docker.com/docker-for-windows/) I gave you, I see that running docker in wsl2 mode should give you direct access to all your windows folders already. Quoting from the instructions:

> The File sharing tab is only available in Hyper-V mode, because in WSL 2 mode and Windows container mode all files are automatically shared by Windows.

So I expect that, in your case, you should be able to write directly to any windows folder.

Best

Giovanni

**Comment by gevero** [comment]
Hi

I just thought of a simpler way of doing everything. Sorry for getting there so late:

- Run the code in binder, as you did in the beginning.
- Let's say that you want to save the scattering spectrum in the np.array `v_csca`. Then you simply save it with `np.savetxt('./filename.txt',v_csca)`
- You than go back to the main jupyter notebook tab and you should see the file you just saved. Select it and a download button will appear.
- If you want to install plotly, just run `! pip install plotly` in a notebook cell.

I am marking this issue as closed.

Best

Giovanni

**Comment by yu-ting-py** [comment]
Hi Giovanni

Thanks a lot! your advice works!
