### ISSUE TITLE
Sphere size limit

### ISSUE THREAD

**Issue by yu-ting-py** [gevero/py_gmm#23]
Hi

I saw your code includes 'electrostatic approximation', right?
So I assume particle size cannot be too big (greater than the wavelength).
Is this true?

**Comment by gevero** [comment]
The code can deal with clusters of spheres of arbitrary size. The `qs_flag` allows to perform a quasi static simulation, in the case you wanted to. `qs_flas='no'` means that you are performing a fully retarded simulation.

Best

Giovanni
