### ISSUE TITLE
User defined dielectric constants

### ISSUE THREAD

**Issue by 1br14n** [gevero/py_gmm#24]
Hi!
In the first line of all the databases that are already included, there is a line at the beginning,
for example in eAuJCSTDf.edb the first line is 

5.9E+28	1.2E-13	1.4E+06

I already check in mat.py and see that the first line is ignored when retrieving the dielectric constants, anyway the question is what about the first line? Is used in another part of the code? If yes, what should I put there? What does represent?
To clarify the context, I'm trying to put an sphere with a tabulated dielectric constant.

Thank you!

**Comment by gevero** [comment]
Hi

The line contained parameters, like carrier density, that were used in a legacy version of the code to compute a dielectric function size correction for very small spheres. It isn't used anymore, and to tell you the truth i did not remember that it was there at all. I will correct the relevant optical constants.

If you want to compute spectra with a tabulated optical constant, just follow one of the examples in the example folder. If you want to include a custom optical constant, just add a file `filename.edb` in the form `wavelenght (nm), eps1, eps2` in the `epsilon` folder. 

Best

Giovanni
