### ISSUE TITLE
Instructions for using Docker

### ISSUE THREAD

**Issue by DAWardle** [gevero/py_gmm#26]
Hi Giovanni.

I've just followed [your instructions](https://github.com/gevero/py_gmm#use-docker) for using py-gmm under Docker.  I'm on a Windows 10 laptop and already had Docker installed (I've used it for a few previous applications).  I encountered one difficulty and have a suggestion to improve (?) your instructions.  Here's my experience following your four steps:

Step 1: I already had Docker installed on my machine --- nothing special about the installation --- I just followed the instructions on the Docker website.

Step 2: Followed and went smoothly --- perhaps it would be helpful to point out that it's about a 2GB download --- helpful for those with limited internet access.

Step 3: Returns a number thus:
`C:\Users\David Wardle>docker run --publish 8888:8888 --detach --name pygmm pygmm:1.0`
`5b734fc03750301ba31dc78f89bba4db0146b774966b9b587dbbb9308dc44ba5`

Step 4: Does return a token:
`C:\Users\David Wardle>docker exec -it pygmm jupyter notebook list`
`Currently running servers:`
`http://0.0.0.0:8888/?token=5e7121e26f30f8985d45d1f072fcbc634ce9ab5e60ac85e0 :: /home/jovyan/notebooks`
But when I paste this into a web browser (I've tried Microsoft Edge and Google Chrome), I get 'ERR_ADDRESS_INVALID'.

If I hadn't used Docker before, I think I would have been stuck.  But I was able to proceed with these amendments to the instructions (maybe you could check they work on a Linux machine?):

Suggestion for Step 3: 'From any directory run:
`docker run --publish 8888:8888 --name pygmm pygmm:1.0`
... which should output a message --- follow the instructions at the end of the message to access Jupyter notebooks in a browser.'

(On my machine I get:
` To access the notebook, open this file in a browser:`
` file:///home/jovyan/.local/share/jupyter/runtime/nbserver-7-open.html`
    `Or copy and paste one of these URLs:`
       ` http://913d32275d7a:8888/?token=2caeba1408b2196df78efd963d4230d6f7f2f920f79859f4`
     `or http://127.0.0.1:8888/?token=2caeba1408b2196df78efd963d4230d6f7f2f920f79859f4`
... and only the last of the three options works --- but, as long as one works, that's fine.)

Step 4 would then be superfluous, although maybe it's worth replacing it with:

Step 4: 'If you have a directory on your computer (for example `C:\Users\JSmith\MyMie`) for which you would like to read and write files, use instead:
`docker run -v C:\Users\JSmith\MyMie:/home/jovyan/notebooks/Shared --publish 8888:8888 --name pygmm pygmm:1.0`
When you open the Jupyter notebooks, you will then find there is a directory 'Shared' that contains your files.'

I hope this is helpful.  Yours sincerely,

David Wardle.

**Comment by gevero** [comment]
Hi David

Thank you for taking the time for opening this issue and for all the helpful observations. As soon as I have a little bit of time I will review the installation procedure with docker and verify and include your suggestions.

Best

Giovanni
