### ISSUE TITLE
How to use py_gmm and jupyter notebook in linux?

### ISSUE THREAD

**Issue by Fly330** [gevero/py_gmm#6]
I'm preliminary for python. After successful installation of the package on anaconda3 with OpenBLAS library, I used the command: `sh f2py.sh` (having changed f2py3 to f2py) to compile py_gmm. Then several complaints appear:
![compile](https://cloud.githubusercontent.com/assets/21698419/18194467/63e92436-7118-11e6-9919-e869d7e02b3f.jpg) And I get a shared library: gmm_py.cpython-35m-x86_64-linux-gnu.so. Have I succeeded to compile py_gmm?
According to the advice in the issue "Cannot find gmm_py module" , I changed the line `sys.path.append('../')`to `sys.path.append('../py_gmm')` in the ~/py_gmm/examples/AuAg_dimer.ipynb file. After that, I use the command: `jupyter notebook AuAg_dimer.ipynb` to run this example. However, the jupyter notebook interface appears:
![error](https://cloud.githubusercontent.com/assets/21698419/18194680/f83e2ebe-7119-11e6-9216-30d76befffd7.jpg)
What can I do next? And how to run this example, AuAg_dimer.ipynb in jupyter notebook interface?

I appreciate any help to get me started.

Thanks,
Yuan

**Comment by gevero** [comment]
Hi Yuan

Here are some instructions:
- Your compilation step is successfull, otherwise you would not get the `gmm_py.cpython-35m-x86_64-linux-gnu.so`. What you see are not complaints, but log informations about the compilation process. I also use linux, so you should not have any problem;
- Do not change the `sys.path.append('../')` line in the notebook, keep it as it is;
- Lauch the jupyter notebook simply with the command line `jupyter notebook`. You can open the relevant notebooks later
- **Enable javascript in your browser** 

After these steps you should be up and running!

Giovanni

**Comment by Fly330** [comment]
Hi Giovanni,
Thanks for your help. I have understood the first three point of the instructions. However it's hard for me to enable javascript in my serve. Please teach me how to enable it in detail.
Regards
Yuan

**Comment by Fly330** [comment]
Additionally, my linux system is centos6.7. Thanks

**Comment by gevero** [comment]
Hi Yuan

Your linux version should not be a problem. So, in the following I will be assuming that your server has no graphic interface, and that you are logging in with `ssh`:
-  ssh in your server and forward port 8888 of the server to your local 8888 port with the following command: `ssh your-user@your-server -L 8888:localhost:8888`
- when your are logged in, launch the jupyter notebook with the following command: `jupyter notebook --no-browser >& notebook_log.txt &`
- open the browser **in your local computer** (ie, chrome, firefox), and point to the address `localhost:8888` or alternatively `127.0.0.1:8888`

and you should be all set.

Giovanni

**Comment by Fly330** [comment]
Hi Giovanni
I appreciate your enthusiastic reply. However, I might not introduce so clearly and make you  misunderstanding. Sorry. 
Actually, My local computer is win7 64-bit system, and I use Xshell to connnect my serve. What should I do?
Regards
Yuan

**Comment by gevero** [comment]
Hi

Then just use xshell to forward `8888` remote port to your `8888` local port. Just follow [this guide](http://www.ahowto.net/windows/easily-create-ssh-tunneling-using-xshell-free-ssh-client/). All the other things (second and third bullet point of my previous answer ) remain the same.

Giovanni

**Comment by gevero** [comment]
@Fly330 

Hi Yuan

Did you solve the problem? Can I close this issue?

Giovanni

**Comment by Fly330** [comment]
Hi Giovanni,
Thanks for your kind reply. I tried to modified settings of Xshell and firebox according to your suggestion.
- I have create a tunnel between my remote serve and firefox browser of the local computer. 
- The browser point to the address `localhost:8888` to open jupyter notebook. 
- I almost succeed to run two examples: AuAg_dimer.ipynb & Stockman Silver Nanolens.ipynb except when importing the libraries, I find the error below:
  ![error](https://cloud.githubusercontent.com/assets/21698419/18298372/b2bcb37c-74ea-11e6-9824-733a5a1ca63d.jpg)
  HELP:
  Would you please give me some detailed suggestions on how to correct this error?

Thanks again for your help and it’s lucky for me to learn from you
Regards
Yuan

**Comment by gevero** [comment]
Hi Yuan

Just `conda install joblib` and you should be ok! Let me know if it's ok so I can close the issue!

Giovanni

**Comment by Fly330** [comment]
Hi Giovanni
According to your suggestions, I installed joblib and all things worked as expected!
Thank you very much!
best
Yuan
